build:
    nodes:
        analysis:
          dependencies:
            override:
              - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -P '!checkerframework,!checkerframework-jdk8,!checkerframework-jdk9orlater' -B -V
        tests:
            environment:
                sdkman:
                  - 'java@11-open'
                timezone: Europe/Paris

            services:
                mysql: 5.7

            dependencies:
              override:
                - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -P '!checkerframework,!checkerframework-jdk8,!checkerframework-jdk9orlater' -B -V

            project_setup:
              override:
                - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -P '!checkerframework,!checkerframework-jdk8,!checkerframework-jdk9orlater' -B -V

            tests:
                override:
                    - command: mysql -u root -e "create database araknemu"
                    - command: mysql -u root -e "create user araknemu"
                    - command: mysql -u root -e "grant all privileges on araknemu.* to araknemu"
                    - command: mvn -P '!checkerframework,!checkerframework-jdk8,!checkerframework-jdk9orlater' test
                      coverage:
                        file: 'target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
                    - command: 'mvn checkstyle:checkstyle'
                      analysis:
                        file: 'target/checkstyle-result.xml'
                        format: 'general-checkstyle'
