name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Paris"

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'araknemu'
          mysql user: 'araknemu'
          mysql password: 'araknemu'

      - name: Reset mysql password
        run: |
          # To prevent "ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0"
          # See: https://github.com/mirromutth/mysql-action/issues/16
          sleep 15

          cat <<EOF | mysql -h 127.0.0.1 -u araknemu --password=araknemu
            UPDATE mysql.user SET authentication_string = null WHERE user = 'araknemu';
            FLUSH PRIVILEGES;
          EOF

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
