package fr.quatrevieux.araknemu.data.living.entity;

import fr.quatrevieux.araknemu.data.value.ItemTemplateEffectEntry;

import java.util.List;

/**
 * Base item type for item storage
 */
public interface Item {
    /**
     * The entry id
     * The id is unique for the bank, and generated by an increment
     *
     * Part of the primary key
     */
    public int entryId();

    /**
     * The item template id
     *
     * @see fr.quatrevieux.araknemu.data.world.entity.item.ItemTemplate#id()
     */
    public int itemTemplateId();

    /**
     * Effects of the item
     */
    public List<ItemTemplateEffectEntry> effects();

    /**
     * The item quantity
     */
    public int quantity();

    /**
     * Change the quantity
     *
     * @param quantity New quantity. Must be positive
     */
    public void setQuantity(int quantity);
}
